<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QE31605" name="Test" tests="10" failures="1" timestamp="29 Sep 2017 16:57:23 GMT" time="29.919" errors="0">
  <testcase name="testCase" time="0.046" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.047" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.056" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.004" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.018" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.003" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.003" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.003" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="0.013" classname="com.alg.test.executionengine.Executor"/>
  <testcase name="testCase" time="28.739" classname="com.alg.test.executionengine.Executor">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.alg.test.executionengine.Executor.testCase(Executor.java:183)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testCase -->
</testsuite> <!-- Test -->
